[package]
name = "simple-calc"
description = "A simple command line calculator"
license = "MIT"
repository = "https://github.com/msmoiz/simple-calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
